FROM python:3.7.5-slim-stretch

WORKDIR /app

COPY . /app

# installs dev dependencies with pipfile.lock and to the system's python
RUN pip install pipenv && \
    pipenv install --system --deploy --ignore-pipfile --dev