# Generated by Django 2.2.13 on 2020-07-22 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='evaluation',
            options={'ordering': ['id'], 'verbose_name': 'Evaluation', 'verbose_name_plural': 'Evaluations'},
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='courses.Course'),
        ),
    ]
